### ISSUE TITLE
Keep the status private

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/docsQA-status#8]
- [ ] create a private repo `docsqa_status_datahouse`
- [ ] adapt the `.github/workflows/health_check.yml` to commit the `data.json` to `docsqa_status_datahouse` 

![Image](https://user-images.githubusercontent.com/4329072/179892132-f4385fdf-2f42-4b71-888a-293fbd0af75a.png)

# Reference
https://docs.google.com/drawings/d/1W5ffODtcXsImLp5eonx8bO1MOlWSA0XdKaRpO-2BRlY/edit

**Comment by nan-wang** [comment]
7/25: Add the secrets for cloning the private repo. @nan-wang

**Comment by nan-wang** [comment]
```
      - uses: actions/checkout@v3
        with:
          path: docsQA-status
      - uses: actions/checkout@v3
        with:
          repository: jina-ai/docsQA-status-data
          token: ${{ secrets. DOCSQA_STATUS_TOKEN }}
          path: docsQA-status-data
```
